name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Create environment
        run: |
          conda env create -f environment.yml
          conda activate cfm
      - name: Test notebooks and documentation
        run: |
          pytest --nbval --current-env --doctest-glob="*.rst"
