name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: cfm
           environment-file: environment.yml
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Test notebooks and documentation
        run: |
          pytest --nbval --current-env --doctest-glob="*.rst"
