name: Test notes

on:
  push:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Clone submodules
        run: |
          git submodule update --init --recursive

      - name: Update pip
        run: |
          python -m pip install -U pip

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      # Build the book
      - name: Test the documentation
        run: |
          python -m doctest ./_class-notes/*.md
